import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/config/site.config";
import { PolicyPage } from "@/components/layout/policy-page";

export const metadata: Metadata = {
  title: "Plagiarism Policy",
  description:
    "How BORJSS defines plagiarism, how similarity screening works and why a percentage is not a verdict, self-plagiarism, and what happens when plagiarism is found.",
};

const TOC = [
  { id: "definition", label: "What plagiarism is" },
  { id: "forms", label: "Forms of plagiarism" },
  { id: "self", label: "Self-plagiarism" },
  { id: "screening", label: "Similarity screening" },
  { id: "thresholds", label: "Why a percentage is not a verdict" },
  { id: "acceptable", label: "Quoting and paraphrasing properly" },
  { id: "before", label: "Found before publication" },
  { id: "after", label: "Found after publication" },
  { id: "language", label: "Translation and language" },
  { id: "avoiding", label: "Avoiding the problem" },
];

export default function Page() {
  return (
    <PolicyPage
      slug="plagiarism"
      title="Plagiarism Policy"
      lead="Every submission is screened for similarity to published work. This policy explains what the journal is looking for, why a similarity percentage is not by itself a finding, and what follows when plagiarism is confirmed."
      toc={TOC}
      related={["publication-ethics", "research-integrity", "retraction-correction"]}
    >
      <h2 id="definition">What plagiarism is</h2>
      <p>
        Plagiarism is presenting another person&rsquo;s words, ideas, data,
        structure or images as though they were your own. It does not require
        intent to deceive, and it is not limited to copied sentences: an
        argument taken from an uncited source is plagiarism even when every word
        is original.
      </p>
      <p>
        The obligation is to make clear, at the point of use, what came from
        elsewhere and where it came from. A source listed in the reference list
        but not cited where it was used does not satisfy this.
      </p>

      <h2 id="forms">Forms of plagiarism</h2>
      <div className="not-prose">
        <dl className="divide-y divide-border rounded-lg border border-brand-border">
          {[
            [
              "Verbatim copying",
              "Reproducing text from a source without quotation marks and a citation.",
            ],
            [
              "Mosaic plagiarism",
              "Weaving phrases from a source into your own sentences without attribution — often the hardest form to detect and the easiest to commit accidentally.",
            ],
            [
              "Inadequate paraphrase",
              "Rewording a passage while keeping its structure and sequence, with or without a citation.",
            ],
            [
              "Plagiarism of ideas",
              "Presenting another's argument, framework, hypothesis or interpretation as your own.",
            ],
            [
              "Data and figure plagiarism",
              "Reusing another's dataset, table, figure or image without attribution and, where required, permission.",
            ],
            [
              "Uncited translation",
              "Translating a passage from another language and presenting it as original writing.",
            ],
            [
              "Citation padding",
              "Listing sources in the reference list that were not read or used, to suggest a depth of engagement that is not there.",
            ],
            [
              "Undisclosed AI text",
              "Presenting text generated by an AI tool as one's own writing — see the AI-assisted writing policy.",
            ],
          ].map(([term, value]) => (
            <div
              key={term}
              className="grid gap-1 px-4 py-3 sm:grid-cols-[16rem_1fr] sm:gap-4"
            >
              <dt className="text-sm font-medium text-muted-foreground">
                {term}
              </dt>
              <dd className="min-w-0 break-words text-sm">{value}</dd>
            </div>
          ))}
        </dl>
      </div>

      <h2 id="self">Self-plagiarism</h2>
      <p>
        Reusing substantial passages from your own earlier publication without
        citing it is text recycling, and the journal treats it as a form of
        plagiarism. The reader is entitled to know what is new.
      </p>
      <p>
        The journal applies this proportionately. Some reuse is unavoidable and
        unobjectionable:
      </p>
      <ul>
        <li>
          <strong>Normally acceptable</strong> — a method description reused
          where the method is genuinely the same, with the earlier paper cited;
          standard definitions; a short restatement of your own prior findings,
          cited.
        </li>
        <li>
          <strong>Not acceptable</strong> — reusing an introduction, literature
          review, discussion or conclusion; republishing findings already
          published elsewhere without disclosure; splitting one study across
          papers that share question, dataset and method.
        </li>
      </ul>
      <p>
        A manuscript developed from your own thesis, working paper, conference
        paper or preprint is welcome. Declare the relationship at submission and
        cite the earlier version; the journal does not treat prior circulation
        as prior publication. The broader question of dividing work across
        papers is covered in the{" "}
        <Link href="/policies/research-integrity">
          research integrity policy
        </Link>
        .
      </p>

      <h2 id="screening">Similarity screening</h2>
      <p>
        Every manuscript is screened for similarity to published work at desk
        check, before it is sent for review, as part of the checks described in
        the <Link href="/policies/peer-review">peer review policy</Link>.
        Manuscripts may be screened again before acceptance where they have been
        substantially rewritten.
      </p>
      <p>
        Screening produces a report showing which passages match which sources.
        That report is read by a member of the editorial office — it is not
        acted on automatically, and no decision is taken from the summary figure
        alone.
      </p>

      <h2 id="thresholds">Why a percentage is not a verdict</h2>
      <p>
        The journal does not publish a threshold percentage, and does not accept
        or reject manuscripts on the basis of one. A single figure is not
        evidence of anything on its own:
      </p>
      <ul>
        <li>
          A manuscript can score 30% entirely on correctly quoted and cited
          material, standard method wording, common phrasing and the reference
          list — and contain no plagiarism at all;
        </li>
        <li>
          A manuscript can score 4% on one uncited paragraph carrying the
          paper&rsquo;s central argument — and be seriously plagiarised;
        </li>
        <li>
          Plagiarism of ideas, of translated material, and of an unpublished
          source produces no similarity match whatever.
        </li>
      </ul>
      <p>
        What the editorial office looks at is therefore the matched text itself:
        where the overlap sits in the manuscript, whether it is quoted and
        cited, whether it is one continuous passage or scattered common phrases,
        and whether it carries substantive content or is boilerplate. That
        judgement is what determines the outcome.
      </p>

      <h2 id="acceptable">Quoting and paraphrasing properly</h2>
      <ul>
        <li>
          <strong>Quotation.</strong> Reproduce the wording exactly, inside
          quotation marks or as an indented block, with a citation including the
          page number. Extended quotation may also need the copyright
          holder&rsquo;s permission — see the{" "}
          <Link href="/policies/copyright">copyright policy</Link>.
        </li>
        <li>
          <strong>Paraphrase.</strong> Restate the point in your own structure
          and vocabulary, having set the source aside, and cite it. If your
          sentence tracks the original clause by clause, it is not a paraphrase
          however many synonyms it contains.
        </li>
        <li>
          <strong>Summary.</strong> Compress an argument in your own terms, with
          a citation. Where you continue to draw on the same source across a
          passage, make that clear rather than citing once at the end.
        </li>
        <li>
          <strong>Figures, tables and instruments.</strong> Cite the source, and
          obtain written permission where the material is under copyright.
          &ldquo;Adapted from&rdquo; requires the same permission as
          reproduction.
        </li>
      </ul>

      <h2 id="before">Found before publication</h2>
      <p>
        The response is proportionate to what the matched text shows, following
        the procedure in the{" "}
        <Link href="/policies/publication-ethics">
          publication ethics policy
        </Link>
        . The corresponding author is always shown the specific passages and
        given a fair opportunity to respond.
      </p>
      <ol>
        <li>
          <strong>Minor and apparently unintentional</strong> — missing
          quotation marks, a citation in the wrong place, or a weak paraphrase
          in a few sentences. The manuscript is returned for correction, with
          the passages identified. This is treated as a fixable fault.
        </li>
        <li>
          <strong>Substantial</strong> — extended uncited passages, or reuse of
          another&rsquo;s argument or data. The manuscript is rejected, and the
          reason recorded.
        </li>
        <li>
          <strong>Serious</strong> — copying that indicates deliberate
          appropriation of another&rsquo;s work. The manuscript is rejected, the
          author&rsquo;s institution is informed, and further submissions may be
          declined for a stated period.
        </li>
      </ol>

      <h2 id="after">Found after publication</h2>
      <p>
        Concerns about a published article are investigated however long ago it
        appeared. The authors are asked to respond, and where the concern is
        serious an expression of concern may be published while the matter is
        examined.
      </p>
      <p>
        Where plagiarism is confirmed, the journal publishes a correction if the
        problem is confined to specific passages that can be properly
        attributed, and retracts the article where the plagiarism is extensive
        or goes to the substance of the work. The article is not removed: a
        retracted article stays available, marked as retracted, under the{" "}
        <Link href="/policies/retraction-correction">
          retraction and correction policy
        </Link>
        . The author&rsquo;s institution is informed, as is the journal in which
        the original work appeared where that is appropriate.
      </p>

      <h2 id="language">Translation and language</h2>
      <p>
        Authors writing in a second language sometimes lean on the phrasing of
        published sources because it is available and correct. This is a common
        route into mosaic plagiarism, and the journal states plainly that it is
        still plagiarism — but it also recognises the pressure that produces it.
      </p>
      <p>
        The remedy is language support, not borrowed sentences. Where an
        author&rsquo;s meaning is clear but the expression is not, the journal
        would rather receive imperfect original prose and recommend language
        editing than receive fluent text assembled from other people&rsquo;s.
        Where a passage matched at screening reads as this rather than as
        appropriation, it is handled under the minor category above.
      </p>
      <p>
        Translating a passage from another language without citing it is
        plagiarism in the ordinary sense, and is not covered by this leniency.
      </p>

      <h2 id="avoiding">Avoiding the problem</h2>
      <ul>
        <li>
          Record the source and page number at the moment you take a note, and
          mark in your notes whether it is a quotation or your own summary;
        </li>
        <li>
          Write the passage from your understanding rather than with the source
          open in front of you;
        </li>
        <li>
          Cite at the point of use, not only in the reference list at the end;
        </li>
        <li>
          Cite your own earlier work as you would anyone else&rsquo;s, and
          declare any overlap at submission;
        </li>
        <li>
          Obtain permission for reproduced figures, tables and instruments
          before you submit, not after acceptance;
        </li>
        <li>
          If in doubt about whether an overlap needs declaring, write to the
          editorial office at{" "}
          <a href={`mailto:${siteConfig.contact.editorialOffice}`}>
            {siteConfig.contact.editorialOffice}
          </a>{" "}
          before submitting. A declared overlap is a routine matter; a
          discovered one is not.
        </li>
      </ul>
      <p>
        Detailed preparation guidance is in the{" "}
        <Link href="/for-authors/guidelines">author guidelines</Link>.
      </p>
    </PolicyPage>
  );
}
